import "@monorepo/ui/globals.css";

import type { Metadata } from "next";
import { Nunito } from 'next/font/google'
import { ThemeProvider } from "../providers/theme-provider";
const nunito = Nunito({
  subsets: ['latin'],
})
 
export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Ravinder's Drive",
  icons: {
    icon: "drive-logo.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={nunito.className} >
        <head>
       
       <link rel="icon" className="rounded-[50%]" href="/drive-logo.svg" sizes="any" />
     </head>
      <body suppressHydrationWarning>
        
        <ThemeProvider attribute="class" 
        defaultTheme="dark"
        enableSystem>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
